### ISSUE TITLE
Utah Sex Offender Registry Form is out of date

### ISSUE THREAD

**Issue by Darunada** [Darunada/namechangr#7]
The form needs to be updated with the newest version issued by BCI.  I reached out to BCI for a docx formatted version and they said talk to the court.  The court said BCI provides the form so talk to them.  Ah government.  Someone good with Word will need to recreate it in docx format, since I can't fill a PDF, I think.

**Comment by briancabbott** [comment]
> The form needs to be updated with the newest version issued by BCI. I reached out to BCI for a docx formatted version and they said talk to the court. The court said BCI provides the form so talk to them. Ah government. Someone good with Word will need to recreate it in docx format, since I can't fill a PDF, I think.

I can help you out with this Lea.

**Comment by Darunada** [comment]
That would be fantastic, if you could call to find the form in docx, figure a way to form fill PDFs, or recreate the updated form as a docx that would all solve the problem!
