### ISSUE TITLE
Google AdWords mobile alert

### ISSUE THREAD

**Issue by Darunada** [Darunada/namechangr#8]
Google Adwords sent me an alert that the sign in and login buttons are too close together for mobile users.  We need to add a bit of space between the Register Now and Log In buttons on the home page.

![image](https://user-images.githubusercontent.com/1255918/64924531-e3523480-d7a2-11e9-9179-95ac0c88710e.png)

**Comment by M4rcinJ** [comment]
Hi, I would like to take care of this one. Let me know if you still need help with it.

**Comment by Darunada** [comment]
This was resolved with PR #9
